# ImmoEliza - XG Boost

After an exploration of several models, XG Boost turned out to provide the best results. Therefore this notebook is a seperate flow of this model.

If you want to rerun the model for a different property type (see below), you will need to import the dataframe again.

**Caveats:**
* At the moment this model only includes numerical variables (such as number of bedrooms or area of the plot) not categorical variables (such as building condition, heating type or EPC). 
* The model does not use any form of scaling.

In [1]:
#import libraries 
import re
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import xgboost as xg

In [2]:
#import dataframe and display first rows and the total number of columns and rows
df = pd.read_csv('../data/saved_data.csv', index_col=0)
display(df.head())
df.shape

property_type property_subtype  immo code Location  Postcode  \
0         house            house   10666428    essen      2910   
1         house            house   10666426  bierges      1301   
2     apartment        apartment   10666424    arlon      6700   
3         house            house   10666423    arlon      6700   
4     apartment        apartment   10666422  antwerp      2000   

         Province    Region    Price               Address Energy class  ...  \
0       Antwerpen  Flanders   469000  Heidestatiestraat 26            D  ...   
1  Brabant wallon  Wallonia  1395000      Rue de Wavre, 27            C  ...   
2      Luxembourg  Wallonia   285000  Avenue de Longwy 340            D  ...   
3      Luxembourg  Wallonia   285000  Avenue de Longwy 340            D  ...   
4       Antwerpen  Flanders   425000   Grote steenweg, 511            C  ...   

   Construction year  Building condition  Bedrooms  Bathrooms  Shower rooms  \
0                  0                   0         3          1             0   
1               1988                Good         5          2             3   
2                  0                Good         2          2             0   
3                  0                Good         2          2             0   
4                  0              As new         2          1             0   

   Office  Toilets    Kitchen type Heating type  Price_orig  
0       0        2       Installed            0     €469000  
1       1        4  Hyper equipped     Fuel oil    €1395000  
2       0        2       Installed     Electric     €285000  
3       0        2       Installed     Electric     €285000  
4       0        0       Installed            0     €425000  

[5 rows x 27 columns]

(6623, 27)

### Select properties by (sub)type
You can hardly compare a kot to a castle. Therefore you can run the model for different property (sub)types. This model is limited to housing types so commercial and industrial buildings are excluded. It uses the types and subtypes set by Immoweb. There are two main types, 'house' and 'apartment' with the following subtypes: 

* house: house, villa, mixed-use-building, exceptional-property, other-property, country-cottage, mansion, town-house, bungalow, farmhouse, new-real-estate-project-houses, chalet, manor-house, castle
* apartment: apartment, service-flat, duplex, triplex, apartment-block, loft, ground-floor, new-real-estate-project-apartments, kot, penthouse, flat-studio

By changing the codeblock below, you can select which (sub)types you want to include (==) or exclude (!=). By default castles are excluded from the model. If you want to change this selection, you should start by reloading the original data by rerunning the codeblock above.

In [3]:

df = df[df.property_type == 'apartment']
#df = df[df.property_type == 'house']
df = df[df.property_subtype != 'castle'] #by default we exclude castles from our model 

In [4]:
print(df.shape)
display(df.head())

(2417, 27)


property_type property_subtype  immo code  \
2      apartment        apartment   10666424   
4      apartment        apartment   10666422   
15     apartment     service-flat   10666397   
20     apartment        apartment   10506515   
21     apartment        apartment   10506513   

                                 Location  Postcode         Province  \
2                                   arlon      6700       Luxembourg   
4                                 antwerp      2000        Antwerpen   
15  les%20bons%20villers%20villers-perwin      6210          Hainaut   
20                                  aalst      9300  Oost-Vlaanderen   
21                                  aalst      9300  Oost-Vlaanderen   

      Region   Price                  Address Energy class  ...  \
2   Wallonia  285000     Avenue de Longwy 340            D  ...   
4   Flanders  425000      Grote steenweg, 511            C  ...   
15  Wallonia  170000  Place Emile Delalieux 1            B  ...   
20  Flanders  125000           Brusselbaan 90            F  ...   
21  Flanders  125000           Brusselbaan 90            C  ...   

    Construction year  Building condition  Bedrooms  Bathrooms  Shower rooms  \
2                   0                Good         2          2             0   
4                   0              As new         2          1             0   
15               2018              As new         1          1             1   
20                  0                Good         1          1             0   
21                  0       To be done up         1          1             0   

    Office  Toilets   Kitchen type Heating type  Price_orig  
2        0        2      Installed     Electric     €285000  
4        0        0      Installed            0     €425000  
15       0        1      Installed          Gas     €170000  
20       0        1  Semi equipped          Gas     €125000  
21       0        0  Semi equipped          Gas     €125000  

[5 rows x 27 columns]

### Define model variables


In [5]:
#int_columns=['Bedrooms', 'Furnished', 'Terrace', 'Terrace surface', 'Surface of the plot', 'Living room surface', 'Number of frontages', 'Construction year', 'Bathrooms', 'Shower rooms', 'Office', 'Toilets']
int_columns=['Bedrooms', 'Terrace', 'Terrace surface', 'Surface of the plot', 'Living room surface', 'Number of frontages', 'Construction year', 'Bathrooms', 'Shower rooms', 'Office', 'Toilets', 'Primary energy consumption']
#int_columns=["Bedrooms", "Bathrooms", "Toilets"]

X = df[int_columns].to_numpy()
y = df.Price.to_numpy().reshape(-1,1)
print(type(X))
print(X)


<class 'numpy.ndarray'>
[[  2.   0.   0. ...   0.   2. 299.]
 [  2.   1.   4. ...   0.   0. 254.]
 [  1.   1.   8. ...   0.   1. 106.]
 ...
 [  3.   1.   7. ...   0.   1. 318.]
 [  6.   1.  60. ...   0.   6. 216.]
 [  3.   1.   9. ...   0.   0. 120.]]


### Split the dataset

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=41)
print("Shape of X_train: ", X_train.shape)
print("Shape of X_test: ", X_test.shape)
print("Shape of y_train: ", y_train.shape)
print("Shape of y_test: ", y_test.shape)

Shape of X_train:  (1933, 12)
Shape of X_test:  (484, 12)
Shape of y_train:  (1933, 1)
Shape of y_test:  (484, 1)


##  Load and fit the model (with Sklearn)

In [7]:
XG_model = "XG Boost"

XG_regressor = xg.XGBRegressor(objective ='reg:linear', n_estimators = 10, seed = 20)
"""X_train = X_train.reshape(-1,1)
X_test = X_test.reshape(-1,1)"""
XG_regressor.fit(X_train, y_train)
XG_train_score = XG_regressor.score(X_train, y_train)
XG_test_score = XG_regressor.score(X_test,y_test)
XG_y_pred = XG_regressor.predict(X_test)
XG_R_MSE = mean_squared_error(y_test, XG_y_pred, squared = False)

[14:25:14] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0fdc6d574b9c0d168-1\xgboost\xgboost-ci-windows\src\objective\regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.


In [8]:
"""pseudocode

XG_regressor opslaan
in API model importeren 
XG_regressor.predict toepassen op API-input"""

'pseudocode\n\nXG_regressor opslaan\nin API model importeren \nXG_regressor.predict toepassen op API-input'

### Scores

In [9]:
model_score_list = ["model", "train_score", "test_score", "R_MSE"]

data = [[XG_model, XG_train_score, XG_test_score, XG_R_MSE]]
newscore_df = pd.DataFrame(data, columns=model_score_list)
#score_df = score_df.join(newscore_df, on=['model'], how='right')
#score_df ["train_score", "test_score", "R_MSE"] = newscore_df ["train_score", "test_score", "R_MSE"]
score_df=newscore_df
display(score_df)

model  train_score  test_score          R_MSE
0  XG Boost     0.725044    0.389665  353305.160897

### Save Model

In [10]:
XG_regressor.save_model('../models/xg_model.json')