# ImmoEliza - Data Modelling

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns 
import plotly.express as px

In [2]:
df = pd.read_csv('../data/saved_data_myt.csv', index_col=0)

In [3]:
df

Type of property               Location  Postcode  immo code    Price  \
0               house                  essen      2910   10666428   469000   
1               house                bierges      1301   10666426  1395000   
2           apartment                  arlon      6700   10666424   285000   
3               house                  arlon      6700   10666423   285000   
4           apartment                antwerp      2000   10666422   425000   
...               ...                    ...       ...        ...      ...   
8589            house                tremelo      3120   10642957   499000   
8590            villa                schilde      2970   10642946  1199000   
8591           duplex  bierbeek%20korbeek-lo      3360   10531808   450000   
8593            house               wevelgem      8560   10642937   340000   
8594            villa                lubbeek      3210   10642929  2395000   

                     Address  Bedrooms Energy class  \
0       Heidestatiestraat 26         3            D   
1           Rue de Wavre, 27         5            C   
2       Avenue de Longwy 340         2            D   
3       Avenue de Longwy 340         2            D   
4        Grote steenweg, 511         2            C   
...                      ...       ...          ...   
8589    Schrieksebaan 53B001         3            D   
8590      Donksesteenweg 212         6            B   
8591  Herbert Hooverplein 14         3            B   
8593           Markeplaats 9         4            B   
8594    Brusselsesteenweg 66         2            B   

      Primary energy consumption  Furnished  ...  Shower rooms  Office  \
0                          390.0          0  ...             0       0   
1                          178.0          0  ...             3       1   
2                          299.0          0  ...             0       0   
3                          299.0          0  ...             0       0   
4                          254.0          0  ...             0       0   
...                          ...        ...  ...           ...     ...   
8589                       383.0          0  ...             0       1   
8590                       199.0          0  ...             0       0   
8591                       120.0          0  ...             0       0   
8593                       161.0          0  ...             0       0   
8594                       197.0          0  ...             3       1   

      Toilets    Kitchen type  Heating type   Price2 Price_orig  Terrace2  \
0           2       Installed             0   469000    €469000         1   
1           4  Hyper equipped      Fuel oil  1395000   €1395000         1   
2           2       Installed      Electric   285000    €285000         0   
3           2       Installed      Electric   285000    €285000         0   
4           0       Installed             0   425000    €425000         1   
...       ...             ...           ...      ...        ...       ...   
8589        2       Installed             0   499000    €499000         1   
8590        3       Installed           Gas  1199000   €1199000         1   
8591        0  Hyper equipped           Gas   450000    €450000         1   
8593        0               0             0   340000    €340000         1   
8594        4  Hyper equipped             0  2395000   €2395000         1   

             Province    Region  
0           Antwerpen  Flanders  
1      Brabant wallon  Wallonia  
2          Luxembourg  Wallonia  
3          Luxembourg  Wallonia  
4           Antwerpen  Flanders  
...               ...       ...  
8589   Vlaams-Brabant  Flanders  
8590        Antwerpen  Flanders  
8591   Vlaams-Brabant  Flanders  
8593  West-Vlaanderen  Flanders  
8594   Vlaams-Brabant  Flanders  

[6623 rows x 29 columns]

In [4]:
df.shape

(6623, 29)

### pastebin:

'Bedrooms',
 'Furnished',
 'Terrace',
 'Terrace surface',
 'Surface of the plot',
 'Living room surface',
 'Number of frontages',
 'Construction year',
 'Outdoor parking space',
 'Bathrooms',
 'Shower rooms',
 'Office',
 'Toilets'


 df.drop(columns=['Price', 'Address',
 'Energy class',
 'Primary energy consumption',
 'Building condition',
 'Kitchen type',
 'Heating type',
 'Price_orig',
 'Province',
 'Region']).to_numpy()

### Define model variables

In [5]:
#X = np.array(df['Bedrooms'])
#int_columns=['Bedrooms', 'Furnished', 'Terrace', 'Terrace surface', 'Surface of the plot', 'Living room surface', 'Number of frontages', 'Construction year', 'Outdoor parking space', 'Bathrooms', 'Shower rooms', 'Office', 'Toilets']
int_columns=['Bedrooms', 'Terrace', 'Terrace surface', 'Surface of the plot', 'Living room surface', 'Number of frontages', 'Construction year', 'Outdoor parking space', 'Bathrooms', 'Shower rooms', 'Office', 'Toilets', 'Primary energy consumption']
#int_columns=["Bedrooms", "Bathrooms", "Toilets"]
X = df[int_columns].to_numpy()
#x_1 = df.drop(columns=["x_2","y"]).to_numpy()
#x_2 = df.drop(columns=["x_1","y"]).to_numpy()
y = df.Price.to_numpy().reshape(-1,1)
print(type(X))
print(X)


<class 'numpy.ndarray'>
[[  3.   1.   0. ...   0.   2. 390.]
 [  5.   1.  60. ...   1.   4. 178.]
 [  2.   0.   0. ...   0.   2. 299.]
 ...
 [  3.   1.   9. ...   0.   0. 120.]
 [  4.   1.   0. ...   0.   0. 161.]
 [  2.   1.  60. ...   1.   4. 197.]]


cropped_df = df[int_columns]
cropped_df["Price"] = df["Price"]
#display(cropped_df)
#sns.pairplot(data=df, y_vars = "Price", x_vars = int_columns, height=5)
sns.pairplot(data=cropped_df)

### Split the dataset

You now know the process!

**Exercise :** Import `train_test_split` from `sklearn` and split the dataset and create the variables `X_train`, `X_test`, `y_train`, `y_test`.

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [7]:
print("Shape of X_train: ", X_train.shape)
print("Shape of X_test: ", X_test.shape)
print("Shape of y_train: ", y_train.shape)
print("Shape of y_test: ", y_test.shape)

Shape of X_train:  (5298, 13)
Shape of X_test:  (1325, 13)
Shape of y_train:  (5298, 1)
Shape of y_test:  (1325, 1)


##  Load and fit the model (with Sklearn)

In [8]:
from sklearn.linear_model import LinearRegression

regressor = LinearRegression()
"""X_train = X_train.reshape(-1,1)
X_test = X_test.reshape(-1,1)"""
regressor.fit(X_train, y_train)

LinearRegression()

In [20]:
from sklearn.tree import DecisionTreeRegressor

regressor = DecisionTreeRegressor()
"""X_train = X_train.reshape(-1,1)
X_test = X_test.reshape(-1,1)"""
regressor.fit(X_train, y_train)

DecisionTreeRegressor()

In [21]:
regressor.score(X_train, y_train)

0.9998310856409685

In [15]:
y_pred = regressor.predict(X_test)

In [16]:
regressor.score(X_test,y_test)

0.29980797365353107

### Mean Squared Error

In [22]:
from sklearn.metrics import mean_squared_error

mean_squared_error(y_test, y_pred, squared = False)

422738.83470956323